export const analyticsDashboardKeys = {
  all: ['analytics-dashboard'] as const,
  applications: () => [...analyticsDashboardKeys.all, 'applications'] as const,
  warRooms: (app: string, month: string) => [...analyticsDashboardKeys.all, 'war-rooms', app, month] as const,
  criticalIncidents: (app: string, month: string) => [...analyticsDashboardKeys.all, 'critical-incidents', app, month] as const,
  moduleEvolution: (app: string, startDate: string, endDate: string) => [...analyticsDashboardKeys.all, 'module-evolution', app, startDate, endDate] as const,
  stabilityIndicators: (app: string, month: string) => [...analyticsDashboardKeys.all, 'stability-indicators', app, month] as const,
  categoryDistribution: (app: string, month: string) => [...analyticsDashboardKeys.all, 'category-distribution', app, month] as const,
  businessFlowPriority: (app: string, month: string) => [...analyticsDashboardKeys.all, 'business-flow-priority', app, month] as const,
  priorityByApp: (app: string, month: string) => [...analyticsDashboardKeys.all, 'priority-by-app', app, month] as const,
  l3TicketsByStatus: (app: string, month: string) => [...analyticsDashboardKeys.all, 'l3-tickets-by-status', app, month] as const,
  incidentsByWeek: (app: string, month: string) => [...analyticsDashboardKeys.all, 'incidents-by-week', app, month] as const,
  incidentsByDay: (app: string, month: string) => [...analyticsDashboardKeys.all, 'incidents-by-day', app, month] as const,
  incidentOverview: (app: string, startDate: string, endDate: string) => [...analyticsDashboardKeys.all, 'incident-overview', app, startDate, endDate] as const,
  l3Summary: (app: string, month: string) => [...analyticsDashboardKeys.all, 'l3-summary', app, month] as const,
  l3RequestsByStatus: (app: string, month: string) => [...analyticsDashboardKeys.all, 'l3-requests-by-status', app, month] as const,
  missingScopeByParent: (app: string, month: string) => [...analyticsDashboardKeys.all, 'missing-scope-by-parent', app, month] as const,
  bugsByParent: (app: string, month: string) => [...analyticsDashboardKeys.all, 'bugs-by-parent', app, month] as const,
  sessionsOrdersLast30Days: (app: string, month: string) => [...analyticsDashboardKeys.all, 'sessions-orders-last-30-days', app, month] as const,
  incidentsVsOrdersByMonth: (app: string, month: string) => [...analyticsDashboardKeys.all, 'incidents-vs-orders-by-month', app, month] as const,
  incidentsByReleaseByDay: (app: string, month: string) => [...analyticsDashboardKeys.all, 'incidents-by-release-by-day', app, month] as const,
  changeReleaseByModule: (app: string, month: string) => [...analyticsDashboardKeys.all, 'change-release-by-module', app, month] as const,
};
